name: CI/CD

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  check-functions:
    name: Check Affected Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: List Changed Directories
        id: changed-dirs
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/merge
          git diff --name-only HEAD FETCH_HEAD | grep "^cloud-function/" | cut -d/ -f2 | sort -u > changed-dirs.txt
          echo "Changed Directories:"
          cat changed-dirs.txt

      - name: Upload Changed Directories
        uses: actions/upload-artifact@v2
        with:
          name: changed-dirs
          path: changed-dirs.txt

  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    needs: [check-functions]

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v2

      - name: Download Changed Directories
        uses: actions/download-artifact@v2
        with:
          name: changed-dirs

      - name: Run Build, Test, and ESLint in Function Directories
        run: |
          affected_functions="$(cat changed-dirs.txt)"
          while IFS= read -r dir; do
            echo "Working in directory: $dir"
            cd "cloud-function/$dir"
            npm install -g yarn
            yarn install
            yarn run eslint
            yarn run build
            yarn run test
            cd -
          done < changed-dirs.txt

  deploy:
    name: Deploy Affected Functions
    runs-on: ubuntu-latest

    needs: [ci]

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v2

      - name: Download Changed Directories
        uses: actions/download-artifact@v2
        with:
          name: changed-dirs

      - name: Auth With GCP
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Deploy Cloud Functions
        run: |
          affected_functions="$(cat changed-dirs.txt)"
          for function_name in $affected_functions; do
            # Deploy the Cloud Function using the function_name
            cd "cloud-function/$function_name"
            gcloud functions deploy "$function_name" \
              --gen2 \
              --runtime=nodejs20 \
              --region=us-central1 \
              --source=. \
              --entry-point="$function_name"Function \
              --trigger-http \
              --allow-unauthenticated
            cd -
          done